"project_id": "792140"
"api_token": "${CROWDIN_TOKEN}"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [{
  "source" : "/translation/de/**/*.json",    # DE ist jetzt Source
  "translation" : "/translation/%locale%/**/%original_file_name%"
}]

- name: crowdin-action
  uses: crowdin/github-action@v2.7.0